apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
  namespace: nextcloud
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextcloud
  # replicas: 1 # Replicas are not needed when using HPA
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: lscr.io/linuxserver/nextcloud:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 443
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: Europe/Copenhagen
        volumeMounts:
        - name: nextcloud-config
          mountPath: /config
        - name: nextcloud-data
          mountPath: /data
      volumes:
      - name: nextcloud-config
        persistentVolumeClaim:
          claimName: nextcloud-config-pvc
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: oci-bv
  resources:
    requests:
      storage: 10Gi
