apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: nextcloud
type: Opaque
data:
  root-password: cm9vdA== # root encoded in base64
  user-password: dXNlcg== # user encoded in base64
